name: Arduino CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: [arduino:avr:uno, arduino:avr:mega, esp32:esp32:esp32]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1.3.1
        with:
          version: latest

      - name: Install cores
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli core install esp32:esp32

      - name: Install library dependencies
        run: |
          arduino-cli lib install "SomeDependency" || true

      - name: Compile examples
        run: |
          for sketch in $(find ./examples -name '*.ino'); do
            echo "Compiling $sketch for ${{ matrix.board }}"
            arduino-cli compile --fqbn ${{ matrix.board }} $sketch
          done

